=== Neox-1990/OpenDECL-Diplom/XML-Spezifikation/openDECL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.tu-dresden.de"
xmlns="http://www.tu-dresden.de"
elementFormDefault="qualified">
<xs:complexType name="porttype">
  <xs:attribute name="id" type="xs:ID" use="required" />
  <xs:attribute name="type" type="xs:string" use="optional" />
  <xs:attribute name="slot" type="xs:string" use="optional" />
</xs:complexType>

<xs:complexType name="graphic-devicetype">
  <xs:sequence>
    <xs:element name="port" type="porttype" minOccurs="1" maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="gpu-count" type="xs:integer" use="optional" />
  <xs:attribute name="vram" type="xs:integer" use="optional" />
  <xs:attribute name="model-name" type="xs:string" use="optional" />
</xs:complexType>

<xs:complexType name="network-devicetype">
  <xs:attribute name="type" type="xs:string" use="required" />
  <xs:attribute name="id" type="xs:IDREF" use="required" />
  <xs:attribute name="address" type="xs:string" use="required" />
</xs:complexType>

<xs:complexType name="nodetype">
  <xs:sequence>
    <xs:element name="graphic-device" type="graphic-devicetype" minOccurs="0" maxOccurs="unbounded" />
	<xs:element name="network-device" type="network-devicetype" minOccurs="0" maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="name" type="xs:ID" use="required" />
  <xs:attribute name="purpose" type="xs:string" use="optional" />
</xs:complexType>

<xs:complexType name="networktype">
  <xs:attribute name="id" type="xs:ID" use="required" />
  <xs:attribute name="bandwidth" type="xs:string" use="optional" />
  <xs:attribute name="subnet-mask" type="xs:string" use="optional" />
</xs:complexType>

<xs:complexType name="vectortype">
  <xs:attribute name="x" type="xs:decimal" use="required" />
  <xs:attribute name="y" type="xs:decimal" use="required" />
  <xs:attribute name="z" type="xs:decimal" use="optional" />
</xs:complexType>

<xs:complexType name="positiontype">
  <xs:sequence>
    <xs:element name="vector" type="vectortype" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="orientationtype">
  <xs:sequence>
    <xs:element name="vector" type="vectortype" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="usertype">
  <xs:sequence>
    <xs:element name="position" type="positiontype" minOccurs="1" maxOccurs="1" />
    <xs:element name="orientation" type="orientationtype" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="upper-lefttype">
  <xs:sequence>
    <xs:element name="vector" type="vectortype" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="lower-lefttype">
 <xs:sequence>
    <xs:element name="vector" type="vectortype" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="lower-righttype">
 <xs:sequence>
    <xs:element name="vector" type="vectortype" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="upper-righttype">
 <xs:sequence>
    <xs:element name="vector" type="vectortype" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="physicaltype">
  <xs:sequence>
    <xs:element name="upper-left" type="upper-lefttype" minOccurs="1" maxOccurs="1" />
    <xs:element name="lower-left" type="lower-lefttype" minOccurs="1" maxOccurs="1" />
    <xs:element name="lower-right" type="lower-righttype" minOccurs="1" maxOccurs="1" />
    <xs:element name="upper-right" type="upper-righttype" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="virtualtype">
 <xs:sequence>
    <xs:element name="upper-left" type="upper-lefttype" minOccurs="1" maxOccurs="1" />
    <xs:element name="lower-left" type="lower-lefttype" minOccurs="1" maxOccurs="1" />
    <xs:element name="lower-right" type="lower-righttype" minOccurs="1" maxOccurs="1" />
    <xs:element name="upper-right" type="upper-righttype" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
</xs:complexType>

<xs:simpleType name="stereoType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="none" />
    <xs:enumeration value="left-eye" />
    <xs:enumeration value="right-eye" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="displaytype">
  <xs:sequence>
    <xs:element name="physical" type="physicaltype" minOccurs="1" maxOccurs="1" />
    <xs:element name="virtual" type="virtualtype" minOccurs="1" maxOccurs="1" />
  </xs:sequence>
  <xs:attribute name="id" type="xs:IDREF" use="required" />
  <xs:attribute name="type" type="xs:string" use="optional" />
  <xs:attribute name="stereo" type="stereoType" use="required" />
  <xs:attribute name="pixel-size-x" type="xs:positiveInteger" use="required" />
  <xs:attribute name="pixel-size-y" type="xs:positiveInteger" use="required" />
  <xs:attribute name="metric-size-x" type="xs:decimal" use="required" />
  <xs:attribute name="metric-size-y" type="xs:decimal" use="required" />
</xs:complexType>

<xs:complexType name="display-setuptype">
  <xs:sequence>
	<xs:element name="user" type="usertype" minOccurs="0" maxOccurs="1" />
    <xs:element name="display" type="displaytype" minOccurs="1" maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="name" type="xs:ID" use="required" />
  <xs:attribute name="eye-distance" type="xs:decimal" default="0.0" />
</xs:complexType>

<xs:complexType name="openDECLtype">
  <xs:sequence>
    <xs:element name="node" type="nodetype" minOccurs="1" maxOccurs="unbounded" />
    <xs:element name="network" type="networktype" minOccurs="0" maxOccurs="unbounded" />
    <xs:element name="display-setup" type="display-setuptype" minOccurs="1" maxOccurs="unbounded" />
  </xs:sequence>
</xs:complexType>

<xs:element name="openDECL" type="openDECLtype" />

</xs:schema>

=== Neox-1990/OpenDECL-Diplom/Editor/default-min.xml
<?xml version="1.0" encoding="UTF-8"?><openDECL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.tu-dresden.de" xsi:schemaLocation="http://www.tu-dresden.de openDECL.xsd"><node name="node1"></node><display-setup name="setup1"><display id="display1" stereo="none" pixel-size-x="1280" pixel-size-y="720" metric-size-x="0.256" metric-size-y="0.144"><physical><upper-left><vector x="-0.128" y="0.072" z="-0.5"></vector></upper-left><lower-left><vector x="-0.128" y="-0.072" z="-0.5"></vector></lower-left><lower-right><vector x="0.128" y="-0.072" z="-0.5"></vector></lower-right><upper-right><vector x="0.128" y="0.072" z="-0.5"></vector></upper-right></physical><virtual><upper-left><vector x="0" y="0"></vector></upper-left><lower-left><vector x="0" y="720"></vector></lower-left><lower-right><vector x="1280" y="720"></vector></lower-right><upper-right><vector x="1280" y="0"></vector></upper-right></virtual></display></display-setup></openDECL>

=== Neox-1990/OpenDECL-Diplom/Abgabe/Diplom RonaldGroßmann/project/bin/temp.output.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><openDECL xmlns="http://www.tu-dresden.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tu-dresden.de openDECL.xsd"><node id="node"/><display-setup id="ds"><display id="display" metric-size-x="0.128" metric-size-y="0.072" pixel-size-x="1280" pixel-size-y="720" portref="unknown" stereo="none"><physical><upper-left><vector x="-0.064" y="0.036" z="-1.0"/></upper-left><lower-left><vector x="-0.064" y="-0.036" z="-1.0"/></lower-left><lower-right><vector x="0.064" y="-0.036" z="-1.0"/></lower-right><upper-right><vector x="0.064" y="0.036" z="-1.0"/></upper-right></physical><virtual><upper-left><vector x="0" y="0"/></upper-left><lower-left><vector x="0" y="720"/></lower-left><lower-right><vector x="1280" y="720"/></lower-right><upper-right><vector x="1280" y="0"/></upper-right></virtual></display></display-setup></openDECL>

=== Neox-1990/OpenDECL-Diplom/Editor/Stereo-Wall.xml
<?xml version="1.0" encoding="UTF-8"?>
<openDECL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.tu-dresden.de" xsi:schemaLocation="http://www.tu-dresden.de openDECL.xsd">
	<node id="Brigitte" purpose="render">
		<graphics-device id="video1">
			<port type="display" id="left"></port>
			<port type="display" id="right"></port>
		</graphics-device>
		<network-device type="ethernet" id="EA1" network="e1" address="127.0.0.1" />
	</node>
	<network id="e1" bandwidth="10 Gbit/s" subnet-mask="255.255.255.0" />
	<display-setup id="stereo" eye-distance="0.06">
		<user>
			<position>
				<vector x="0" y="0" z="0"></vector>
			</position>
			<orientation>
				<vector x="0" y="0" z="-1"></vector>
			</orientation>
		</user>
		<display id="projL" portref="left" type="projector" stereo="left-eye" pixel-size-x="1400" pixel-size-y="1050" metric-size-x="0.4" metric-size-y="0.3">
			<physical>
				<upper-left>
					<vector x="-2.0" y="0.15" z="-0.2"></vector>
				</upper-left>
				<lower-left>
					<vector x="-2.0" y="-0.15" z="-0.2"></vector>
				</lower-left>
				<lower-right>
					<vector x="-2.0" y="-0.15" z="0.2"></vector>
				</lower-right>
				<upper-right>
					<vector x="-2.0" y="0.15" z="0.2"></vector>
				</upper-right>
			</physical>
			<virtual>
				<upper-left>
					<vector x="0" y="0"></vector>
				</upper-left>
				<lower-left>
					<vector x="0" y="1050"></vector>
				</lower-left>
				<lower-right>
					<vector x="1400" y="1050"></vector>
				</lower-right>
				<upper-right>
					<vector x="1400" y="0"></vector>
				</upper-right>
			</virtual>
		</display>
		<display id="MonL" portref="left" type="monitor" stereo="left-eye" pixel-size-x="1400" pixel-size-y="1050" metric-size-x="2.72" metric-size-y="2.04">
			<physical>
				<upper-left>
					<vector x="-1.36" y="1.02" z="-1.0"></vector>
				</upper-left>
				<lower-left>
					<vector x="-1.36" y="-1.02" z="-1.0"></vector>
				</lower-left>
				<lower-right>
					<vector x="1.36" y="-1.02" z="-1.0"></vector>
				</lower-right>
				<upper-right>
					<vector x="1.36" y="1.02" z="-1.0"></vector>
				</upper-right>
			</physical>
			<virtual>
				<upper-left>
					<vector x="0" y="0"></vector>
				</upper-left>
				<lower-left>
					<vector x="0" y="1050"></vector>
				</lower-left>
				<lower-right>
					<vector x="1400" y="1050"></vector>
				</lower-right>
				<upper-right>
					<vector x="1400" y="0"></vector>
				</upper-right>
			</virtual>
		</display>
		<display id="projR" portref="right" type="projector" stereo="right-eye" pixel-size-x="1400" pixel-size-y="1050" metric-size-x="2.72" metric-size-y="2.04">
			<physical>
				<upper-left>
					<vector x="-1.36" y="1.02" z="-1.0"></vector>
				</upper-left>
				<lower-left>
					<vector x="-1.36" y="-1.02" z="-1.0"></vector>
				</lower-left>
				<lower-right>
					<vector x="1.36" y="-1.02" z="-1.0"></vector>
				</lower-right>
				<upper-right>
					<vector x="1.36" y="1.02" z="-1.0"></vector>
				</upper-right>
			</physical>
			<virtual>
				<upper-left>
					<vector x="1400" y="0"></vector>
				</upper-left>
				<lower-left>
					<vector x="1400" y="1050"></vector>
				</lower-left>
				<lower-right>
					<vector x="2800" y="1050"></vector>
				</lower-right>
				<upper-right>
					<vector x="2800" y="0"></vector>
				</upper-right>
			</virtual>
		</display>
	</display-setup>
</openDECL>

=== Neox-1990/OpenDECL-Diplom/source/OpenDECL Editor/temp2.output.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><openDECL xmlns="http://www.tu-dresden.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tu-dresden.de openDECL.xsd">
	<node id="Brigitte" purpose="render">
		<graphics-device id="video1">
			<port id="left" type="display"/>
			<port id="right" type="display"/>
		</graphics-device>
		<network-device address="127.0.0.1" id="EA1" network="e1" type="ethernet"/>
	</node>
	<network bandwidth="10 Gbit/s" id="e1" subnet-mask="255.255.255.0"/>
	<display-setup eye-distance="0.06" id="stereo">
		<user>
			<position>
				<vector x="0" y="0" z="0"/>
			</position>
			<orientation>
				<vector x="0" y="0" z="-1"/>
			</orientation>
		</user>
		<display id="projL" metric-size-x="0.4" metric-size-y="0.3" pixel-size-x="1400" pixel-size-y="1050" portref="left" stereo="left-eye" type="projector">
			<physical>
				<upper-left>
					<vector x="-2.0" y="0.15" z="-0.2"/>
				</upper-left>
				<lower-left>
					<vector x="-2.0" y="-0.15" z="-0.2"/>
				</lower-left>
				<lower-right>
					<vector x="-2.0" y="-0.15" z="0.2"/>
				</lower-right>
				<upper-right>
					<vector x="-2.0" y="0.15" z="0.2"/>
				</upper-right>
			</physical>
			<virtual>
				<upper-left>
					<vector x="0" y="0"/>
				</upper-left>
				<lower-left>
					<vector x="0" y="1050"/>
				</lower-left>
				<lower-right>
					<vector x="1400" y="1050"/>
				</lower-right>
				<upper-right>
					<vector x="1400" y="0"/>
				</upper-right>
			</virtual>
		</display>
		<display id="MonL" metric-size-x="2.72" metric-size-y="2.04" pixel-size-x="1400" pixel-size-y="1050" portref="left" stereo="left-eye" type="monitor">
			<physical>
				<upper-left>
					<vector x="-1.36" y="1.02" z="-1.0"/>
				</upper-left>
				<lower-left>
					<vector x="-1.36" y="-1.02" z="-1.0"/>
				</lower-left>
				<lower-right>
					<vector x="1.36" y="-1.02" z="-1.0"/>
				</lower-right>
				<upper-right>
					<vector x="1.36" y="1.02" z="-1.0"/>
				</upper-right>
			</physical>
			<virtual>
				<upper-left>
					<vector x="0" y="0"/>
				</upper-left>
				<lower-left>
					<vector x="0" y="1050"/>
				</lower-left>
				<lower-right>
					<vector x="1400" y="1050"/>
				</lower-right>
				<upper-right>
					<vector x="1400" y="0"/>
				</upper-right>
			</virtual>
		</display>
		<display id="projR" metric-size-x="2.72" metric-size-y="2.04" pixel-size-x="1400" pixel-size-y="1050" portref="right" stereo="right-eye" type="projector">
			<physical>
				<upper-left>
					<vector x="-1.36" y="1.02" z="-1.0"/>
				</upper-left>
				<lower-left>
					<vector x="-1.36" y="-1.02" z="-1.0"/>
				</lower-left>
				<lower-right>
					<vector x="1.36" y="-1.02" z="-1.0"/>
				</lower-right>
				<upper-right>
					<vector x="1.36" y="1.02" z="-1.0"/>
				</upper-right>
			</physical>
				<upper-left>
					<vector x="1400" y="0"/>
				</upper-left>
				<lower-left>
					<vector x="1400" y="1050"/>
				</lower-left>
				<lower-right>
					<vector x="2800" y="1050"/>
				</lower-right>
				<upper-right>
					<vector x="2800" y="0"/>
				</upper-right>
			</virtual>
		</display>
	</display-setup>
</openDECL>

=== Neox-1990/OpenDECL-Diplom/Editor/Ronald-Desktop.xml
<?xml version="1.0" encoding="UTF-8"?>
<openDECL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.tu-dresden.de" xsi:schemaLocation="http://www.tu-dresden.de openDECL.xsd">
	<node name="Ronald-PC" address="127.0.0.1" purpose="render">
		<device type="graphics-card" gpu-count="1" vram="512" model-name="ATi Radeon HD 3650 mobility">
			<port type="display" id="M1" slot="0"></port>
			<port type="display" id="M2" slot="HDMI 1"></port>
		</device>
		<device type="network-card">
			<port type="ethernet" id="e1"></port>
		</device>
	</node>
	<network id="e1" bandwidth="10 Gbit/s" subnet-mask="255.255.255.0"></network>
	<display-setup name="flat">
		<user>
			<position>
				<vector x="0" y="0" z="0"></vector>
			</position>
			<orientation>
				<vector x="0" y="0" z="-1"></vector>
			</orientation>
		</user>
		<display id="M1" type="monitor" stereo="none" pixel-size-x="1280" pixel-size-y="800" metric-size-x="0.32" metric-size-y="0.2">
			<physical>
				<upper-left>
					<vector x="-0.32" y="0.1" z="-0.5"></vector>
				</upper-left>
				<lower-left>
					<vector x="-0.32" y="-0.1" z="-0.5"></vector>
				</lower-left>
				<lower-right>
					<vector x="0" y="-0.1" z="-0.5"></vector>
				</lower-right>
				<upper-right>
					<vector x="0" y="0.1" z="-0.5"></vector>
				</upper-right>
			</physical>
			<virtual>
				<upper-left>
					<vector x="0" y="0"></vector>
				</upper-left>
				<lower-left>
					<vector x="0" y="800"></vector>
				</lower-left>
				<lower-right>
					<vector x="1280" y="800"></vector>
				</lower-right>
				<upper-right>
					<vector x="1280" y="0"></vector>
				</upper-right>
			</virtual>
		</display>
		<display id="M2" type="monitor" stereo="none" pixel-size-x="1920" pixel-size-y="1080" metric-size-x="0.464" metric-size-y="0.26">
			<physical>
				<upper-left>
					<vector x="0" y="0.13" z="-0.5"></vector>
				</upper-left>
				<lower-left>
					<vector x="0" y="-0.13" z="-0.5"></vector>
				</lower-left>
				<lower-right>
					<vector x="0.464" y="-0.13" z="-0.5"></vector>
				</lower-right>
				<upper-right>
					<vector x="0.464" y="0.13" z="-0.5"></vector>
				</upper-right>
			</physical>
			<virtual>
				<upper-left>
					<vector x="1280" y="0"></vector>
				</upper-left>
				<lower-left>
					<vector x="1280" y="1080"></vector>
				</lower-left>
				<lower-right>
					<vector x="3200" y="1080"></vector>
				</lower-right>
				<upper-right>
					<vector x="3200" y="0"></vector>
				</upper-right>
			</virtual>
		</display>
	</display-setup>
</openDECL>
