=== Neox-1990/OpenDECL-Diplom/XML-Spezifikation/prototyp1.dtd
<!ELEMENT openDECL (node+,network*,display-setup+)>
<!ELEMENT node (device+)>
<!ELEMENT device (port+)>
<!ELEMENT port EMPTY>
<!ELEMENT network EMPTY>
<!ELEMENT display-setup (display+)>
<!ELEMENT display (physical,virtual)>
<!ELEMENT physical (upper-left-vector,lower-left-vector,lower-right-vector,upper-right-vector)>
<!ELEMENT virtual (upper-left-vector,lower-left-vector,lower-right-vector,upper-right-vector)>
<!ELEMENT upper-left-vector EMPTY>
<!ELEMENT lower-left-vector EMPTY>
<!ELEMENT lower-right-vector EMPTY>
<!ELEMENT upper-right-vector EMPTY>

<!ATTLIST node name CDATA #REQUIRED>
<!ATTLIST node address CDATA #REQUIRED>
<!ATTLIST node purpose CDATA #IMPLIED>

<!ATTLIST device type (graphics-card|network-card|other) "graphics-card">
<!ATTLIST device gpu-count CDATA #IMPLIED>
<!ATTLIST device vram CDATA #IMPLIED>
<!ATTLIST device model-name CDATA #IMPLIED>

<!ATTLIST port id ID #REQUIRED>
<!ATTLIST port type CDATA #IMPLIED>
<!ATTLIST port slot CDATA #IMPLIED>

<!ATTLIST network id IDREFS #REQUIRED>
<!ATTLIST network bandwidth CDATA #IMPLIED>
<!ATTLIST network subnet-mask CDATA #IMPLIED>

<!ATTLIST display-setup name ID #REQUIRED>
<!ATTLIST display-setup eye-distance CDATA "0.0">

<!ATTLIST display id IDREF #REQUIRED>
<!ATTLIST display stereo (none|left-eye|right-eye) "none">
<!ATTLIST display pixel-size-x CDATA #REQUIRED>
<!ATTLIST display pixel-size-y CDATA #REQUIRED>
<!ATTLIST display metric-size-x CDATA #REQUIRED>
<!ATTLIST display metric-size-y CDATA #REQUIRED>
<!ATTLIST display type CDATA #IMPLIED>

<!ATTLIST upper-left-vector x CDATA #REQUIRED>
<!ATTLIST upper-left-vector y CDATA #REQUIRED>
<!ATTLIST upper-left-vector z CDATA "0">

<!ATTLIST lower-left-vector x CDATA #REQUIRED>
<!ATTLIST lower-left-vector y CDATA #REQUIRED>
<!ATTLIST lower-left-vector z CDATA "0">

<!ATTLIST lower-right-vector x CDATA #REQUIRED>
<!ATTLIST lower-right-vector y CDATA #REQUIRED>
<!ATTLIST lower-right-vector z CDATA "0">

<!ATTLIST upper-right-vector x CDATA #REQUIRED>
<!ATTLIST upper-right-vector y CDATA #REQUIRED>
<!ATTLIST upper-right-vector z CDATA "0">

=== Neox-1990/OpenDECL-Diplom/XML-Spezifikation/CAVE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE openDECL SYSTEM "prototyp1.dtd">
<openDECL>
	<node name="Cave-Front-1" address="192.168.100.1" purpose="render">
		<device type="graphics-card" gpu-count="1" vram="768" model-name="Nvidia quadro 4600">
			<port type="display" id="P3-1" slot="DVI 1" />
		</device>
		<device type="network-card">
			<port type="ethernet" id="e1" />
		</device>
	</node>
	<node name="Cave-Front-2" address="192.168.100.2" purpose="render">
		<device type="graphics-card" gpu-count="1" vram="768" model-name="Nvidia quadro 4600">
			<port type="display" id="P3-2" slot="DVI 1" />
		</device>
		<device type="network-card">
			<port type="ethernet" id="e2" />
		</device>
	</node>
	<node name="Cave-Left-1" address="192.168.100.3" purpose="render">
		<device type="graphics-card" gpu-count="1" vram="768" model-name="Nvidia quadro 4600">
			<port type="display" id="P2-1" slot="DVI 1" />
		</device>
		<device type="network-card">
			<port type="ethernet" id="e3" />
		</device>
	</node>
	<node name="Cave-Left-2" address="192.168.100.4" purpose="render">
		<device type="graphics-card" gpu-count="1" vram="768" model-name="Nvidia quadro 4600">
			<port type="display" id="P2-2" slot="DVI 1" />
		</device>
		<device type="network-card">
			<port type="ethernet" id="e4" />
		</device>
	</node>
	<network id="e1 e2 e3 e4" bandwidth="10 Gbit/s" subnet-mask="255.255.255.0" />
	<display-setup name="Zwei-Seiten-Cave">
		<display id="P3-1" type="projector" stereo="none" pixel-size-x="1600" pixel-size-y="1200" metric-size-x="3.6" metric-size-y="2.7">
			<physical>
				<upper-left-vector x="-1.8" y="1.35" z="-1.8" />
				<lower-left-vector x="-1.8" y="-1.35" z="-1.8" />
				<lower-right-vector x="1.8" y="-1.35" z="-1.8" />
				<upper-right-vector x="1.8" y="1.35" z="-1.8" />
			</physical>
			<virtual>
				<upper-left-vector x="0" y="0" />
				<lower-left-vector x="0" y="1200" />
				<lower-right-vector x="1600" y="1200" />
				<upper-right-vector x="1600" y="0" />
			</virtual>
		</display>
		<display id="P2-1" type="projector" stereo="none" pixel-size-x="1600" pixel-size-y="1200" metric-size-x="3.6" metric-size-y="2.7">
			<physical>
				<upper-left-vector x="-1.8" y="1.35" z="1.8" />
				<lower-left-vector x="-1.8" y="-1.35" z="1.8" />
				<lower-right-vector x="-1.8" y="-1.35" z="-1.8" />
				<upper-right-vector x="-1.8" y="1.35" z="-1.8" />
			</physical>
			<virtual>
				<upper-left-vector x="0" y="0" />
				<lower-left-vector x="0" y="1200" />
				<lower-right-vector x="1600" y="1200" />
				<upper-right-vector x="1600" y="0" />
			</virtual>
		</display>
	</display-setup>
</openDECL>

=== Neox-1990/OpenDECL-Diplom/XML-Spezifikation/Stereo-Wall.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE openDECL SYSTEM "prototyp1.dtd">
<openDECL>
	<node name="Brigitte" address="127.0.0.1" purpose="render">
		<device type="graphics-card" gpu-count="1" vram="512" model-name="eine tolle Grafikkarte">
			<port type="display" id="P1" slot="HDMI 1" />
			<port type="display" id="P2" slot="HDMI 2" />
		</device>
		<device type="network-card">
			<port type="ethernet" id="e1" />
		</device>
	</node>
	<network id="e1" bandwidth="10 Gbit/s" subnet-mask="255.255.255.0" />
	<display-setup name="Side-by-Side-Stereo" eye-distance="0.06">
		<display id="P1" type="projector" stereo="left-eye" pixel-size-x="1400" pixel-size-y="1050" metric-size-x="2.72" metric-size-y="2.04">
			<physical>
				<upper-left-vector x="-1.36" y="1.02" z="-2" />
				<lower-left-vector x="-1.36" y="-1.02" z="-2" />
				<lower-right-vector x="1.36" y="-1.02" z="-2" />
				<upper-right-vector x="1.36" y="1.02" z="-2" />
			</physical>
			<virtual>
				<upper-left-vector x="0" y="0" />
				<lower-left-vector x="0" y="1050" />
				<lower-right-vector x="1400" y="1050" />
				<upper-right-vector x="1400" y="0" />
			</virtual>
		</display>
		<display id="P2" type="projector" stereo="right-eye" pixel-size-x="1400" pixel-size-y="1050" metric-size-x="2.72" metric-size-y="2.04">
			<physical>
				<upper-left-vector x="-1.36" y="1.02" z="-2" />
				<lower-left-vector x="-1.36" y="-1.02" z="-2" />
				<lower-right-vector x="1.36" y="-1.02" z="-2" />
				<upper-right-vector x="1.36" y="1.02" z="-2" />
			</physical>
			<virtual>
				<upper-left-vector x="1400" y="0" />
				<lower-left-vector x="1400" y="1050" />
				<lower-right-vector x="2800" y="1050" />
				<upper-right-vector x="2800" y="0" />
			</virtual>
		</display>
	</display-setup>
</openDECL>
